# Generated by Django 5.2.5 on 2025-09-13 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresettokens',
            old_name='account',
            new_name='cuenta',
        ),
    ]
