# Generated by Django 5.2.5 on 2025-09-14 01:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_rename_comentarios_comentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentario',
            new_name='AlertaComentario',
        ),
        migrations.RenameModel(
            old_name='Prioridad',
            new_name='AlertaEstado',
        ),
        migrations.RenameModel(
            old_name='Estado',
            new_name='AlertaPrioridad',
        ),
    ]
