# Generated by Django 5.2.5 on 2025-09-14 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0003_rename_comentario_alertacomentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.alertaestado'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='prioridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.alertaprioridad'),
        ),
    ]
