# Generated by Django 5.2.5 on 2025-09-13 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAmenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Amenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False)),
                ('codigoMitre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=300)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.categoriaamenaza')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
