# Generated by Django 5.2.5 on 2025-09-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenazas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaAmenaza',
            new_name='AmenazaCategoria',
        ),
    ]
