# Generated by Django 5.2.5 on 2025-09-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenazas', '0002_rename_categoriaamenaza_amenazacategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenaza',
            name='categoria',
        ),
        migrations.AddField(
            model_name='amenaza',
            name='categorias',
            field=models.ManyToManyField(related_name='amenazas', to='amenazas.amenazacategoria'),
        ),
    ]
